stages:
  - docs

build_docs:
  stage: docs
  image: python:3.12
  script:
    - python3 -m ensurepip --default-pip
    - python3 -m pip install --upgrade pip --user
    - python3 -m pip install --user fastapi pydantic sphinx sphinx_rtd_theme sphinx-autodoc-typehints
    - cd docs
    - make html
    - cd ..
    - rm -rf public/*
    - cp -r docs/build/html public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main