version: "3.9"

services:
  myapp:
    build: .
    container_name: myapp_container
    env_file:
      - variables.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./logs:/app/logs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"